import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface-dim": "#edd5cb",
        "on-tertiary-container": "#33322f",
        "on-background": "#251913",
        background: "#fff8f6",
        "tertiary-fixed-dim": "#c9c6c1",
        "on-error": "#ffffff",
        primary: "#9d4300",
        "on-error-container": "#93000a",
        "on-secondary-container": "#686361",
        "surface-container": "#ffeae0",
        "surface-bright": "#fff8f6",
        "surface-container-low": "#fff1eb",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "inverse-surface": "#3c2d26",
        "on-primary-container": "#582200",
        "secondary-fixed-dim": "#ccc5c2",
        "on-surface-variant": "#584237",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#4a4643",
        surface: "#fff8f6",
        "surface-tint": "#9d4300",
        "on-surface": "#251913",
        "tertiary-container": "#9d9a95",
        "primary-fixed-dim": "#ffb690",
        "on-secondary-fixed": "#1e1b19",
        "inverse-on-surface": "#ffede6",
        "secondary-container": "#e9e1dd",
        secondary: "#625d5b",
        "on-primary": "#ffffff",
        "surface-variant": "#f6ded3",
        "tertiary-fixed": "#e6e2dc",
        "primary-container": "#f97316",
        "primary-fixed": "#ffdbca",
        "surface-container-highest": "#f6ded3",
        "on-primary-fixed-variant": "#783200",
        "inverse-primary": "#ffb690",
        outline: "#8c7164",
        "surface-container-high": "#fce3d9",
        "on-tertiary-fixed-variant": "#484743",
        tertiary: "#605e5a",
        "on-tertiary-fixed": "#1c1c18",
        "outline-variant": "#e0c0b1",
        "secondary-fixed": "#e9e1dd",
        "on-primary-fixed": "#341100",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
      },
      spacing: {
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        "touch-min": "44px",
        gutter: "16px",
        xs: "4px",
        sm: "8px",
        base: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "Inter", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
      },
      boxShadow: {
        glow: "0 0 0 1px rgba(251, 191, 36, 0.12), 0 24px 80px rgba(0, 0, 0, 0.35)",
        stitch: "0 2px 12px -2px rgba(28, 25, 23, 0.08)",
        "login-card": "0 12px 24px -4px rgba(28, 25, 23, 0.12)",
      },
    },
  },
  plugins: [],
};

export default config;
